version: '3.1'

services:
  springboot:
    build: .
    restart: always
    container_name: wechallengeapp
    ports:
      - 8080:8080
    working_dir: /opt/app
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - node.name=es01
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - discovery.seed_hosts=es01
      - bootstrap.memory_lock=true
      - xpack.monitoring.enabled=true
      - xpack.ml.node_concurrent_job_allocations=8
      - http.host=0.0.0.0

  angular:
    build: .
    ports:
      - 5555:5555
    working_dir: /opt/app/angularclient
    command: ng serve --host 0.0.0.0 --port 5555
    depends_on:
      - springboot
